---
- name: ".bashrc.d to {{ dest }}"
  copy:
    src: "{{ item }}"
    dest: "{{ dest }}/.bashrc.d/"
  with_fileglob: Bash/bashrc.d/*bash
- name: ".bash_completion to {{ dest }}"
  copy:
    src: Bash/Completion/bash_completion
    dest: "{{ dest }}/.bash_completion"
- name: "Clone LS_COLORS"
  git:
    repo: "https://github.com/trapd00r/LS_COLORS"
    dest: "~/Dotfiles/Bash/Colors/LS_COLORS"
    clone: true
    update: true
- name: ".dircolors to {{ dest }}"
  copy:
    src: Bash/Colors/LS_COLORS/LS_COLORS
    dest: "{{ dest }}/.dircolors"
- name: ".bashrc for Cygwin"
  copy:
    src: "Cygwin/bashrc"
    dest: "{{ home }}/.bashrc"
  when: ansible_facts.os_family is match("CYGWIN")

# vim: filetype=yaml
