#!/bin/bash

DATE=$(date +%s)
perl -i.bak -p -e "s/^LOCAL_TIMESTAMP=.*/LOCAL_TIMESTAMP=$DATE/" Bash/bashrc.d/0950_checkupdate.bash
git add Bash/bashrc.d/0950_checkupdate.bash
rm Bash/bashrc.d/0950_checkupdate.bash.bak
