#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  connection: local
  vars:
    home: "{{ ansible_env.HOME }}"
  pre_tasks:
    - name: Userprofile on Cygwin
      block:
        - name: cygpath {{ ansible_env.USERPROFILE }}
          command: cygpath '{{ ansible_env.USERPROFILE }}'
          register: cygpath
        - name: Set fact userprofile {{ cygpath.stdout }}
          set_fact:
            userprofile: "{{ cygpath.stdout }}"
      when: ansible_facts.os_family is match("CYGWIN")
    - name: Git submodules
      command: git submodule update --init --recursive --remote
    - name: Remove old git hook
      file:
        path: .git/hooks/pre-commit
        state: absent
  roles:
    - role: Vim
      vars:
        dest: "{{ home }}"
        vimrc: ".vimrc"
        gvimrc: ".gvimrc"
        vimfiles: ".vim"
    - role: Vim
      vars:
        dest: "{{ userprofile }}"
        vimrc: "_vimrc"
        gvimrc: "_gvimrc"
        vimfiles: "vimfiles"
      when: userprofile is defined
    - role: Bash
      vars:
        dest: "{{ home }}"
    - role: Git
    - role: Ansible
    - { role: Gnome, when: ansible_env.DBUS_SESSION_BUS_ADDRESS is defined }
    - { role: LXTerminal, when: ansible_facts.os_family is not match("CYGWIN") }
    - role: Screen
    - { role: Cron, when: ansible_facts.os_family is not match("CYGWIN") }
    - role: Cron
    - role: Yamllint
    - role: MC

# vim: filetype=yaml
