#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  connection: local
  vars:
    home: "{{ ansible_env.HOME }}"
  tasks:
    - name: Userprofile on Cygwin
      block:
        - name: cygpath {{ ansible_env.USERPROFILE }}
          command: cygpath '{{ ansible_env.USERPROFILE }}'
          register: cygpath
        - name: Set fact userprofile {{ cygpath.stdout }}
          set_fact:
            userprofile: "{{ cygpath.stdout }}"
      when: ansible_facts.os_family is match("CYGWIN")
  roles:
    - role: Vim
      vars:
        dest: "{{ home }}"
        vimrc: ".vimrc"
        gvimrc: ".gvimrc"
        vimfiles: ".vim"
    - role: Bash
      vars:
        dest: "{{ home }}"

# vim: filetype=yaml
