#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  become: true
  gather_facts: false
  connection: local
  roles:
  - role: install-apt
    repo:
      source: deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free
      filename: rslsync
    key:
      url: https://linux-packages.resilio.com/resilio-sync/key.asc
      filename: rslsync.asc
    install: 
    - resilio-sync
  - role: install-apt
    repo:
      source: deb https://typora.io/linux ./
      filename: typora
    key:
      url: https://typoraio.cn/linux/public-key.asc
      filename: typora.asc
    install: 
    - typora
  - role: install-apt
    key:
      url: https://keys.anydesk.com/repos/DEB-GPG-KEY
      filename: anydesk.asc
    repo:
      source: deb http://deb.anydesk.com/ all main
      filename: anydesk-stable
    install:
    - anydesk
  - role: install-apt
    repo:
      source: deb [arch=amd64] https://ppa.javinator9889.com all main
      filename: javinator9889-ppa
    key:
      url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xf047de71abd761ba176dc1d508633b4aaaeb49fc
      filename: javinator9889-ppa.asc
    install:
    - discord
  tasks:
  - name: Install misc. useful packages
    apt:
      name: 
      - sysstat 
      - locate 
      - apt-file
      - trash-cli
      - wireshark
      update_cache: true
  - name: Enable sysstat
    lineinfile:
      path: /etc/default/sysstat
      regexp: '^ENABLED'
      line: 'ENABLED="true"'
  - name: Disable resilio system service
    systemd:
      name: resilio-sync
      scope: system
      enabled: no
      state: stopped
  - name: REMOVE THE NANO EDITOR
    apt:
      name: nano
      state: absent
      purge: yes
- hosts: localhost
  become: false
  gather_facts: false
  connection: local
  tasks:
  - name: Resilio drop-in directory
    file:
      path: ~/.config/systemd/user/resilio-sync.service.d/
      state: directory
  - name: Resilio drop-in file (-> WantedBy=default.target)
    copy:
      content: |
        [Install]
        WantedBy=default.target
      dest: ~/.config/systemd/user/resilio-sync.service.d/override.conf
  - name: Enable resilio user service
    systemd:
      name: resilio-sync
      scope: user
      enabled: yes
      state: started

# vim: filetype=yaml
