#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  become: true
  gather_facts: false
  connection: local
  tasks:
  - name: Add liquorix apt source
    apt_repository:
      repo: 'ppa:damentz/liquorix'
      update_cache: true
