all:
	curl -O https://raw.githubusercontent.com/samhocevar/unicode-emoji/master/emoji-test.txt
	curl -L -O https://github.com/ryanoasis/nerd-fonts/releases/latest/download/UbuntuMono.zip
	curl -L -O https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Agave.zip

clean:
	rm *zip
